resources:
  - name: resource_multibranch
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vishnurao12/multibranch
      files: 
        include: ^README.md$
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: testing_12345
    steps:
      - name: myStep112
        type: Bash
        configuration:
#           nodePool: u16test
#           timeoutSeconds: 7200
#           timeoutSeconds: 60
          environmentVariables:
            testCases: 'setup.js'
#           runtime:           
#             type: host
          inputResources: 
            - name: resource_multibranch
          integrations:
            - name: git_v
        execution:
          onStart:
              - env
              - printenv
